---
- name: Configure AlphaMind Infrastructure
  hosts: all
  become: true
  roles:
    - ../roles/common
    - ../roles/security

- name: Configure Database Servers
  hosts: database
  become: true
  roles:
    - ../roles/database

- name: Configure Web Servers
  hosts: webservers
  become: true
  roles:
    - ../roles/webserver
